on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
  watch:
    types: [started]
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Updater
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Nix cache
      uses: actions/cache@v1
      with:
        path: /nix/store
        key: nix_store
    - name: Install Nix
      uses: cachix/install-nix-action@v15
    - name: Run
      run: |
        NIX_PATH=nixpkgs=default.nix time nix-shell --pure --run ./main.py
    - uses: EndBug/add-and-commit@v9 
